# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "dm-cti"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Asher Van Brunt"]
  s.date = "2011-11-03"
  s.description = "Simple Class Table Inheritance for DataMapper"
  s.email = "asher.vanbrunt@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".autotest",
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "test/data.rb",
    "test/helper.rb"
  ]
  s.homepage = "http://github.com/okbreathe/dm-cti"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Simple Class Table Inheritance for DataMapper"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dm-validations>, [">= 1.2.0"])
      s.add_runtime_dependency(%q<dm-constraints>, [">= 1.2.0"])
      s.add_runtime_dependency(%q<dm-ar-finders>, [">= 1.2.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.0"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<minitest-rg>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rr>, [">= 0"])
      s.add_development_dependency(%q<dm-sqlite-adapter>, [">= 1.2.0"])
      s.add_development_dependency(%q<dm-postgres-adapter>, [">= 1.2.0"])
      s.add_development_dependency(%q<dm-migrations>, [">= 1.2.0"])
    else
      s.add_dependency(%q<dm-validations>, [">= 1.2.0"])
      s.add_dependency(%q<dm-constraints>, [">= 1.2.0"])
      s.add_dependency(%q<dm-ar-finders>, [">= 1.2.0"])
      s.add_dependency(%q<activesupport>, [">= 3.0.0"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<minitest-rg>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rr>, [">= 0"])
      s.add_dependency(%q<dm-sqlite-adapter>, [">= 1.2.0"])
      s.add_dependency(%q<dm-postgres-adapter>, [">= 1.2.0"])
      s.add_dependency(%q<dm-migrations>, [">= 1.2.0"])
    end
  else
    s.add_dependency(%q<dm-validations>, [">= 1.2.0"])
    s.add_dependency(%q<dm-constraints>, [">= 1.2.0"])
    s.add_dependency(%q<dm-ar-finders>, [">= 1.2.0"])
    s.add_dependency(%q<activesupport>, [">= 3.0.0"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<minitest-rg>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rr>, [">= 0"])
    s.add_dependency(%q<dm-sqlite-adapter>, [">= 1.2.0"])
    s.add_dependency(%q<dm-postgres-adapter>, [">= 1.2.0"])
    s.add_dependency(%q<dm-migrations>, [">= 1.2.0"])
  end
end

